- message_definitions/v1.0/common.xml
From this [Jira ticket](https://auterion.atlassian.net/browse/AMC-1285?atlOrigin=eyJpIjoiYzI2ZDI2ZGQ1NjY4NDczNjhiZDhmMjBmMTAwNzZmM2IiLCJwIjoiaiJ9)
Moving camera tracking commands and messages from the gimbal api to the camera api. 
I wanted to start on a fork so we could discuss it here before pushing upstream. Note that this fork was quite outdated. As I didn't know what was going on, I first created a branch pulling upstream master (upstream_merge). This PR is against that and not master.
> AMC-1285 Move camera tracking from gimbal to camera api.

- .github/workflows/upstream_sync.yml
Allows to automatically create a PR to sync with upstream mavlink/mavlink. Approval will be required to merge the PR, so making it safe to use.
> Github Actions: add upstream sync workflow

- message_definitions/v1.0/auterion.xml
This PR adds `MAV_CMD_COMPONENT_CONTROL`, a command that serves the purpose of controlling MAVLink system components. We can compare it with simplified version of `systemctl`, which is an utility that makes part of Linux `systemd`, but in this case it can interface with both HW components and also with system services identified by component ID (ex: `MAV_COMP_ID_PATHPLANNER` or `MAV_COMP_ID_OBSTACLE_AVOIDANCE`).
The type of control that can be used is mapped by the `COMPONENT_CONTROL` enumeration, which can be extended for other types of controls if required.
This command can be considered a replacement of `MAV_CMD_PREFLIGHT_REBOOT_SHUTDOWN`, as it provided more control options without restricting ourselves the the limited command fields.
The first usage of this command will be added in …
> message_definitions: auterion: add MAV_CMD_COMPONENT_CONTROL cmd and COMPONENT_CONTROL enum

- message_definitions/v1.0/auterion.xml
- message_definitions/v1.0/development.xml
This will make it easier to upstream the feature. Follows with an update in the mavlink headers in PX4, MAVSDK and AMC.
> Move COMPONENT_CONTROL enum and MAV_CMD_COMPONENT_CONTROL to the 'development' dialect

- scripts/update_c_library.sh
If we generate all the dialects we end up with a build error when trying
to use auterion/mavlink.h:
```
error: "MAVLINK_MESSAGE_INFO" redefined
```
By only generating auterion.xml we don't have that problem.
> scripts: only generate auterion dialect

- message_definitions/v1.0/all.xml
- message_definitions/v1.0/auterion.xml
- message_definitions/v1.0/ras_a.xml
This includes now the RAS-A dialect from the RAS-A IOP. The dialect is being developed and updated in the [air-iop-definitions](https://github.com/Dronecode/air-iop-definitions) repositiory. Auterion dialect now includes `ras_a` instead of `development`.
> Add the RAS-A dialect

- message_definitions/v1.0/development.xml
For some reason, the `MAV_CMD_COMPONENT_CONTROL` just disappeared in some commit some time ago. Bringing also some reorg to the MAV_CMD entries.
> Reorganize development dialect MAV_CMDs

- message_definitions/v1.0/auterion.xml
We do not need the JOYSTICK_INFORMATION message because we can use this [COMPONENT_INFORMATION](https://mavlink.io/en/services/component_information.html) to provide the link to the json file. 
I also moved some fields needed for decoding JOYSTICK_STATE into the JOYSTICK_STATE message. This has the advantage that the json file is only needed for configuring the joystick and not for understanding the state messages. Disadvantage is that we will send these fields at constant rate (probably around 20Hz) even though these stay constant. Please advise if you would rather have them in the json file instead.
FYI @batinkov
> remove JOYSTICK_INFORAMTION message in favor of COMPONENT_INFORMATION

- message_definitions/v1.0/auterion.xml
@potaito we'd like to see our motor flight time in AMC after all. Also I think it makes more sense to use a proper command for "precision loiter" instead of hacking do_change_altitude. I've already updated our PX4/AMC with this. Let me know what you think. We don't have to merge right away but eventually would be nice.
> Added MOTOR_INFO and MAV_CMD_DO_PRECISION_HOLD

- message_definitions/v1.0/development.xml
In a multi GCS environment, only on GCS should be able to control the system. All other GCS should only act as observers. As an observer, you can still receive telemetry and payload stream, get the parameters and the mission, but cannot command the vehicle and change the parameters and mission. In order to set which GCS is in control, new message sets needs to be created.
The proposed solution is detailed as:
- Control can be given for the Flight control and/or the payload
- A control status message is sent from the system at a constant frequency and when the control has been changed. The message is sent to all connected GCS and defines if the GCS is in control, another GCS is in control or none is in control.
- A GCS is always first connected as an obsever.
- A GCS can request control …
> Add control handoff messages for multiple GCS

- message_definitions/v1.0/development.xml
Mutli GCS implementation of the use the settable GCS Callsign as requester_id in the mavlink message. The standard Callsign is already 20 char long. Increased the requester_id char array to hold a longer callsign name. Also increase the reason field o hold longer reason character arrays.
> Increase the character array length of the requester_id and the reason

- message_definitions/v1.0/auterion.xml
- message_definitions/v1.0/common.xml
- message_definitions/v1.0/development.xml
- message_definitions/v1.0/minimal.xml
- message_definitions/v1.0/ras_a.xml
This PR moves custom messages not intended for upstreaming to the auterion dialect, and removes some that we will deprecate in the next auterion px4 release. It also updates the RAS-A dialect to v1.2 https://github.com/Dronecode/air-iop-definitions/releases/tag/v1.2-ras-a_iop.
@mrivi @cmic0 @DanielePettenuzzo @potaito @TSC21 please check that I did not remove or alter something you are not comfortable with.
> Organize auterion mavlink

- message_definitions/v1.0/auterion.xml
- message_definitions/v1.0/development.xml
https://auterion.atlassian.net/browse/VTOL-987
Add a message to log distance to a beacon (radio) and its position, to auterion messages.
This message is part of a bigger scope to improve position estimation in GPS denied environments.
> VTOL-987 Mavlink - define ToF message and send GCS location

- scripts/update_c_library.sh
In a recent automatic upstream merge the ordering of the xml list got messed up. How it was before:
auterion.xml
ardupilotmega.xml
why?
auterion.xml includes ras_a.xml
ras_a.xml includes develop.xml
ardupilotmega.xml includes common.xml (+ uavionix, icarous, cubepilot, csairlink xmls) common.xml includes standard.xml
standard.xml includes minimal.xml
This PR reverts to our previous sequence which should generate the headers we want. But... man... can there be a less convoluted way?? @TSC21 any ideas? (doesnt need to be done for this PR)
> Revert update_c_library.sh

- .github/workflows/test_and_deploy.yml
- examples/c/udp_example.c
- message_definitions/v1.0/auterion.xml
- message_definitions/v1.0/ras_a.xml
- scripts/update_c_library.sh
Need to additionally remove ardupilotmega xml... not sure how this worked before with it included.
Fixes lingering wrongness from #226 
Include tree:
auterion.xml includes ras_a.xml
ras_a.xml includes development.xml
development.xml includes common.xml
**HOLD:**
still need to resolve:
```
Merged enum MAV_COMPONENT
ERROR: Duplicate enum values:
MAV_TYPE.MAV_TYPE_GENERIC_MULTIROTOR = 43 @ /home/thomas/git/PX4_firmware_private/src/modules/mavlink/mavlink/message_definitions/v1.0/minimal.xml:203
MAV_TYPE.MAV_TYPE_GENERIC_COMPONENT = 43 @ /home/thomas/git/PX4_firmware_private/src/modules/mavlink/mavlink/message_definitions/v1.0/ras_a.xml:12
```
(@TSC21 edited: it's done - check https://github.com/Auterion/mavlink/pull/227/commits/9a291322468d4332f2d9a2a6e2ca02cfae97930a).
```
ERROR: Duplicate …
```
> Fix include tree, duplicate message ids, and ci tests

- message_definitions/v1.0/common.xml
- message_definitions/v1.0/development.xml
Upstream PR that we want to merge soon:
https://github.com/mavlink/mavlink/pull/1945
Merged the changes into Auterion's MAVLink fork almost a year ago:
https://github.com/Auterion/mavlink/pull/182
Then removed 3 months ago:
https://github.com/Auterion/mavlink/pull/220/files
But we need it now already. So let's bring it back.
My apologies, and I will make sure we can merge the upstream PR soon.
> Bring back CELLULAR_STATUS

- message_definitions/v1.0/common.xml
This reverts https://github.com/Auterion/mavlink/pull/276, as otherwise we're not compatible with upstream PX4. AMC is now adapting to the new message, so this is no longer needed.
> Revert "bring back smart battery info"

- message_definitions/v1.0/auterion.xml
- message_definitions/v1.0/common.xml
- message_definitions/v1.0/development.xml
These messages will be removed from upstream development and need to be moved to auterion specific xml.
auterion.xml messages were reordered by message id.
> Pr move param transaction protocol

- message_definitions/v1.0/common.xml
- message_definitions/v1.0/development.xml
This PR reverts the breaking standard mode changes. This PR can be reverted as soon as we have `c_library_v2` hash without these changes. 
Current version of APX4 relies on older headers whereas AMC needs the new headers for new message definitions used in OEM PX4 versions.
The issue is that the new headers have one less `MAV_STANDARD_MODE` and the enum values are shifted.
> revert standard mode changes

- message_definitions/v1.0/auterion.xml
This PR adds a CAMERA_TRACKING_REFINEMENT message. The message is used to refine the tracked point in the video stream and is send by AMC in particular when users interact through the Picture-in-Picture (PiP) or utilize keyboard controls to refine tracking.
> Add CAMERA_TRACKING_REFINEMENT message

- message_definitions/v1.0/common.xml
Partially revert #293 to use an integer frame ID instead of a timestamp to identify frames in tracking selections.
The frame ID is a 16-bit integer between 0 and 65535, which can still be stored as a float - the type of the `MAV_CMD` params.
**Jira:** [CV-250](https://auterion.atlassian.net/browse/CV-250)
[CV-250]: https://auterion.atlassian.net/browse/CV-250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Change timestamp to frame ID in tracking selection commands

- .github/workflows/upstream_sync.yml
Upstream merge failed when upstream changes the workflow files. instead of default GITHUB_TOKEN use a specifically design token with proper contents and workflow write rights.
> chore: update ustream sync with correct access rights

- .gitmodules
- message_definitions/v1.0/auterion.xml
This PR is mimicing the upstream PR against mavlink/mavlink(#2255).
Why?
This is because many of the boat specific fields and messages are subject to change, partially because we don't know enough at the time of writing and the created messages are purposefully designed to be very non-restrictive as a result. Also, the implementation associated with them is mostly on the CAN driver side, which stays as Auterion IP and will not be upstreamed.
Also AMC already supports these MAVLink definitinons, but they ought to be based on Auterion managed version control and not a private forks of mavlink repository.
**[new enums]**
ENGINE_LEG_TRIM
- Defines the engine leg state, part of BOAT_ACTUATOR_STATUS message sent from a vehicle to the GCS.
- Data originates from J1939 CAN messages and the engine …
> USV messages for for Auterion dialect
